# Generated by Django 4.2.3 on 2023-07-19 02:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0003_rename_format_document_file_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
